version: '3.9'

services:
  postgres:
    image: postgres
    container_name: rasplus_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rasplus
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=rasplus-db