spring:
      application:
        name: Rasplus

      datasource:
        url: jdbc:postgresql://localhost:5432/rasplus-db
        username: rasplus
        password: senha123

      jpa:
        show-sql: true
        properties:
          hibernate.format_sql: true
        hibernate:
          ddl-auto: update
        open-in-view: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE